blog_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'blog_main.views.custom_page_not_found'
urlpatterns = [
    path('admin/', admin.site.urls),
    path(route="", view=include(arg="my_blog.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/urls.py
from django.urls import path
from my_blog import views

app_name = 'my_blog'

urlpatterns = [path(route="", view=views.index, name='index'),
               path(route="post/<str:slug>", view=views.detail, name='detail'),
               path(route="old_url", view=views.old_url_redirect, name='old_page'),
               path(route="new_page_url", view=views.new_url_page, name='new_page'),
               path(route="contact", view=views.contact, name='contact'),
               path(route="about", view=views.about, name='about'),
               path(route="register", view=views.register_view, name='register_url'),
               path(route="login", view=views.login, name='login'),
               path(route="dashboard", view=views.dashboard, name="dashboard"),
               path(route="logout", view=views.logout_view, name="logout"),
               path(route="forgot_password", view=views.forgot_password, name='forgot_password'),
               path("reset_password/<uidb64>/<token>", views.reset_password, name="reset_password" ),
               path(route="new_post", view=views.new_post, name='new_post'),
               path(route="edit_post/<int:post_id>", view=views.edit_post, name='edit_post'),
               path(route="delete_post/<int:post_id>", view=views.delete_post, name='delete_post'),
               path("publish_post/<int:post_id>", views.publish_post, name="publish_post" )]

my_blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Category
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image_url = models.ImageField(null=True, upload_to="posts/images")
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True)
    is_published = models.BooleanField(default=False)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

# when printing model gives the title
    def __str__(self):
        return self.title


    @property
    def formatted_img_url(self):
        url = self.image_url if self.image_url.__str__().startswith(('http://','https://')) else self.image_url.url
        return url
    
class AboutUs(models.Model):
    content = models.TextField()

my_blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from my_blog.models import Category, Post

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, label='Name', required=True)
    email = forms.EmailField(label='Email', required=True)
    message = forms.CharField(label='Message', required=True)

class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=100, label='username_form', required=True)
    email = forms.EmailField(max_length=100, label='email_form', required=True)
    password = forms.CharField(max_length=100, label='password_form', required=True)
    confirm_password = forms.CharField(max_length=100, label='confirm_password_form', required=True)

    # make a connection between register form and auth_user table(prebuilt)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Password does not match!!!")

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label='username', required=True)
    password = forms.CharField(max_length=100, label='password', required=True)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if user is None:
                raise forms.ValidationError("Invalid username and password")

class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=254, required=True)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("No User Registered with this email.")

class ResetPasswordForm(forms.Form):
    new_password = forms.CharField(label='New Password', min_length=8)
    confirm_password = forms.CharField(label='Confirm Password', min_length=8)

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        if new_password and confirm_password and new_password != confirm_password:
            raise forms.ValidationError(message="Password does not match !!")


class PostForm(forms.ModelForm):
    title = forms.CharField(label='Title', max_length=200, required=True)
    content = forms.CharField(label='Content', required=True)
    category =  forms.ModelChoiceField(label='Category', required=True, queryset=Category.objects.all())
    image_url = forms.ImageField(label='image_url', required=False)

    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'image_url']

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')

        #custom validation
        if title and len(title) < 5:
            raise forms.ValidationError('Title must be at least 5 Characters long.')
        
        if content and len(content) < 10:
            raise forms.ValidationError('Content must be at least 10 Characters long.')
    
    def save(self, commit = ...):

        post =  super().save(commit)
        cleaned_data = super().clean()
        if cleaned_data.get('image_url'):
            post.image_url = cleaned_data.get('image_url')
        else:
            img_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/600px-No_image_available.svg.png"
            post.image_url = img_url    

        if commit:
            post.save()
        return post

my_blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.urls import reverse
from my_blog.models import Post, AboutUs, Category
from my_blog.forms import ContactForm, RegisterForm, LoginForm, ForgotPasswordForm, ResetPasswordForm, PostForm
from django.http import Http404
import logging
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login as auth_login
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group

# Create your views here.

# static demo data
#posts = [{'id': 1, 'title': 'Post 1', 'content': 'Content of post 1'},
#         {'id': 2, 'title': 'Post 2', 'content': 'Content of post 2'},
#         {'id': 3, 'title': 'Post 3', 'content': 'Content of post 3'},
#         {'id': 4, 'title': 'Post 4', 'content': 'Content of post 4'},]

def index(request):
    blog_title = "Venky's Blog"
    # getting data from post model
    all_posts = Post.objects.filter(is_published=True).order_by("created_at")
    # pagenate
    paginator = Paginator(object_list=all_posts, per_page=5)
    page_no = request.GET.get('page')
    page_object = paginator.get_page(number=page_no)
    return render(request=request, template_name='blog/index.html', context={'blog_title': blog_title, 'page_obj': page_object})

def detail(request, slug):
    if request.user and not request.user.has_perm('blog.view_post'):
        messages.error(request, 'You have no permission to view any posts')
        return redirect('my_blog:index')
    # static data
    #post = next((item for item in posts if item['id'] == int(post_id)), None)
    
    try:
        # getting data from model by post id
        post = Post.objects.get(slug=slug)
        related_posts = Post.objects.filter(category=post.category).exclude(pk=post.id)
    except Post.DoesNotExist:
        raise Http404("Post does not exist")
    #logger = logging.getLogger("TESTING")
    #logger.debug(f"Post variable is {post}")
    return render(request=request, template_name='blog/details.html', context={'post': post, 'related_posts': related_posts})

def old_url_redirect(request):
    return redirect(to=reverse(viewname='my_blog:new_page'))      # name from url page

def new_url_page(request):
    return HttpResponse("New Url page")

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        logger = logging.getLogger("TESTING")
        if form.is_valid():
            logger.debug(f'POST Data is {form.cleaned_data['name']} {form.cleaned_data['email']} {form.cleaned_data['message']}')
            #send email or save in database
            success_message = 'Your Email has been sent!'
            return render(request,'blog/contact.html', {'form':form,'success_message':success_message})
        else:
            logger.debug('Form validation failure')
        return render(request,'blog/contact.html', {'form':form, 'name': name, 'email':email, 'message': message})
    return render(request,'blog/contact.html')

def about(request):
    about_content = AboutUs.objects.first()
    if about_content is None or not about_content.content:
        about_content = "Default Content goes here!!!"
    else:
        about_content = about_content.content
    return render(request=request, template_name='blog/about.html', context={'about_content': about_content})

def register_view(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])  # hash the password
            user.save()  # user data is created
            # add user to readers group
            readers_group,created = Group.objects.get_or_create(name="Readers")
            user.groups.add(readers_group)
            messages.success(request, 'Registration successful! You can now log in.')
            print("Registration Successful")
            return redirect(to='my_blog:login')
    return render(request=request, template_name='blog/register.html', context={'form': form})

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request=request, user=user)
                return redirect(to='my_blog:dashboard')
    else:
        form = LoginForm()
    
    return render(request, 'blog/login.html', {'form': form})

def dashboard(request):
    blog_title = "My Posts"
    #getting user posts
    all_posts = Post.objects.filter(user=request.user)

    # paginate
    paginator = Paginator(all_posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request,'blog/dashboard.html', {'blog_title': blog_title, 'page_obj': page_obj})

def logout_view(request):
    logout(request=request)
    return redirect(to="my_blog:index")

def forgot_password(request):
    # Initialize an empty form for the forgot password page
    form = ForgotPasswordForm()

    # Check if the request is a POST request (form submission)
    if request.method == 'POST':
        # Reinitialize the form with data from the request (submitted form data)
        form = ForgotPasswordForm(request.POST)

        # Validate the form to ensure all required fields are filled and correct
        if form.is_valid():
            # Extract the email address submitted by the user
            email = form.cleaned_data['email']

            # Fetch the user object corresponding to the email address
            user = User.objects.get(email=email)

            # Generate a secure token for the user to reset their password
            token = default_token_generator.make_token(user)

            # Encode the user's primary key (ID) in a secure format
            uid = urlsafe_base64_encode(force_bytes(user.pk))

            # Get the current site (domain name) for including in the email
            current_site = get_current_site(request)
            domain = current_site.domain

            # Define the subject of the email
            subject = "Reset Password Requested"

            # Render the email template with required context (domain, uid, token)
            message = render_to_string('blog/reset_password_email.html', {
                'domain': domain,  # Website domain (e.g., example.com)
                'uid': uid,        # Encoded user ID
                'token': token     # Password reset token
            })

            # Send the reset password email to the user
            send_mail(subject, message, '"no_reply@venky.com"', [email])

            # Display a success message to the user
            messages.success(request, 'Email has been sent')

    # Render the forgot password page with the form (either empty or pre-filled on error)
    return render(request, 'blog/forgot_password.html', {'form': form})

def reset_password(request, uidb64, token):
    form = ResetPasswordForm()
    if request.method == 'POST':
        #form
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            try:
                uid = urlsafe_base64_decode(uidb64)
                user = User.objects.get(pk=uid)
            except(TypeError, ValueError, OverflowError, User.DoesNotExist):
                user = None

            if user is not None and default_token_generator.check_token(user, token):
                user.set_password(new_password)
                user.save()
                messages.success(request, 'Your password has been reset successfully!')
                return redirect('my_blog:login')
            else :
                messages.error(request,'The password reset link is invalid')

    return render(request,'blog/reset_password.html', {'form': form})

@login_required 
@permission_required(perm='blog.add_post', raise_exception=True)
def new_post(request):
    categories = Category.objects.all()
    form = PostForm()
    if request.method == 'POST':
        #form
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('my_blog:dashboard')
    return render(request,'blog/new_post.html', {'categories': categories, 'form': form})

@login_required
@permission_required('blog.change_post', raise_exception=True)
def edit_post(request, post_id):
    categories = Category.objects.all()
    post = get_object_or_404(Post, id=post_id)
    form = PostForm()
    if request.method == "POST":
        #form
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Post Updated Succesfully!')
            return redirect('my_blog:dashboard')

    return render(request,'blog/edit_post.html', {'categories': categories, 'post': post, 'form': form})

@login_required
@permission_required('blog.delete_post', raise_exception=True)
def delete_post(request, post_id):

my_blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container-fluid ">
    <h3>About Us</h3>
    <div class="d-flex gap-3 justify-content-center mt-5">
        <img src="https://picsum.photos/300/300" alt="">
        <div class="content">
            {{about_content}}
        </div>
        
    </div>
</div>
{% endblock %}

my_blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog_title | default:'Document' }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css'%}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body >
    <!-- Header -->
    {% include 'blog/includes/header.html' %}

    <!-- Dynamic Content -->
    {% block content %}
    {% endblock %}

    <!-- Footer -->
    {% include 'blog/includes/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

my_blog/templates/blog/dashboard.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container-fluid ">
  <div class="row">
    <div class="col-6">
        <h3> Hi, {{user.username}}.</h3>
    </div>
    <div class="col d-flex justify-content-end">
        <div>
            <h2>Your Groups:</h2>
            <ul>
                {% for group in user.groups.all %}
                <li>{{group.name}}</li>
              {% empty %}
                <li>You are not a member of any groups.</li>
              {% endfor %}
            </ul>
        </div>
    </div>
  </div>
  <div class="row d-flex justify-content-center">
    <div class="col-6">
        {% include 'blog/includes/errors.html' %}
    </div>
  </div>
  <div class="row">
    <h2 class="mt-3">{{blog_title}}</h2>
    {% if perms.blog.add_post %}
    <div class="d-flex justify-content-center">
        <a href="{% url "my_blog:new_post" %}" class="btn btn-success">New Post</a>
    </div>
    {% endif %}
  </div>
  <div class="row m-3">
     {% if page_obj %}
        {% for post in page_obj %}
        <div class="col-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <img style="height:300; width:300;" src="{{post.formatted_img_url}}" class="img-fluid" alt="...">
                        </div>
                        <div class="col-md-8">
                            <h5 class="card-title">{{post.title}}</h5>
                            <p class="card-text">{{post.content|truncatechars:50}}</p>
                            <div class="d-flex justify-content-between">
                                <a href="{% url 'my_blog:detail' slug=post.slug %}">Read More</a>
                                <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                            </div>
                            <div class="d-flex justify-content-between mt-2">
                                {% if perms.blog.change_post %}
                                <a class="btn btn-warning btn-sm" href="{% url 'my_blog:edit_post' post_id=post.id %}">Edit Post</a>
                                {% endif %}
                                {% if perms.blog.delete_post %}
                                <button class="btn btn-danger btn-sm" onclick="confirmDelete('{% url 'my_blog:delete_post' post_id=post.id %}')">Delete Post</button>
                                {% endif %}
                                {% if not post.is_published and perms.blog.can_publish %}
                                <a href="{% url 'my_blog:publish_post' post_id=post.id %}" class="btn btn-success btn-sm">Publish</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="col-12 my-3">
            {% if page_obj.has_other_pages %}
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {%if page_obj.has_previous%}
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="First">
                                    <span aria-hidden="true">&laquo; first</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                    <span aria-hidden="true">previous</span>
                                </a>
                            </li>
                        {%endif%} 
                        <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                        {%if page_obj.has_next%}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                <span aria-hidden="true">last &raquo;</span>
                            </a>
                        </li>
                        {%endif%}
                    </ul>
                </nav>
            {%endif%}
            
        </div>
    {% else %}
        <p>No Posts Available</p>
    {% endif %}  

  </div>
</div>
<script>
    function confirmDelete(url) {
        var userConfirmed = confirm("Are you sure want to delete?")

        if (userConfirmed) {
            window.location.href = url
        }
    }
</script>
{% endblock content %}  

my_blog/templates/blog/details.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}} <small style="font-size:18px">({{post.category.name}})</small></h1>
              <p class="text-muted">Posted on {{post.created_at | date:"F j, Y"}}</p>
              <img src="{{post.formatted_img_url}}" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
              
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    {% for related_post in related_posts %}
                    <li><a href="{% url 'my_blog:detail' slug=related_post.slug %}">{{related_post.title}}</a></li>
                    {% endfor%}
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

my_blog/templates/blog/forgot_password.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-3 mt-3">
                <h2>Forgot Password</h2>
                <div>
                    {% include 'blog/includes/errors.html' %}
                </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="email" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Send Password Reset Email</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

my_blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container-fluid ">
            <div class="row">
                <h2 >{{blog_title }}</h2>
            </div>
            <div class="row m-3">
                {% include "blog/includes/errors.html" %}
                {% if page_obj %}
                    {% for post in page_obj %}
                    <div class="col-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img style="height:300; width:300;" src="{{post.formatted_img_url}}" class="img-fluid" alt="...">
                                    </div>
                                    <div class="col-md-8">
                                        <h5 class="card-title">{{post.title}}</h5>
                                        <p class="card-text">{{post.content|truncatechars:50}}</p>
                                        <div class="d-flex justify-content-between">
                                            <a href="{% url 'my_blog:detail' slug=post.slug %}">Read More</a>
                                            <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="col-12 my-3">
                        {% if page_obj.has_other_pages %}
                            <nav aria-label="Page navigation">
                                <ul class="pagination">
                                    {%if page_obj.has_previous%}
                                        <li class="page-item">
                                            <a class="page-link" href="?page=1" aria-label="First">
                                                <span aria-hidden="true">&laquo; first</span>
                                            </a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                                <span aria-hidden="true">previous</span>
                                            </a>
                                        </li>
                                    {%endif%} 
                                    <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                                    {%if page_obj.has_next%}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                            <span aria-hidden="true">next</span>
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                            <span aria-hidden="true">last &raquo;</span>
                                        </a>
                                    </li>
                                    {%endif%}
                                </ul>
                            </nav>
                        {%endif%}
                        
                    </div>
                {% else %}
                    <p>No Posts Available</p>
                {% endif %}
            </div>
    </div>
{% endblock %}

my_blog/templates/blog/login.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row d-flex justify-content-center mt-5">
        <div class="col-4">
            <h3>Login</h3>
            <div class="">
                {% include "blog/includes/errors.html" %}
                 
                <div class="col-12">
                    <span class="fw-bold"></span>
                    <span class="text-danger"></span>
                </div>
            </div>

            <div class="col-12">
                <span class="text-danger"></span>
            </div>


            <div class="my-3">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" class="form-control" id="username" name="username" value="{{form.username.value | default:""}}">
                    </div>
                   
                    <div class="form-group">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                   
                    <div class="my-3 d-flex justify-content-between">
                        <a href="{% url "my_blog:forgot_password" %}">Forgot Password</a>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

my_blog/templates/blog/reset_password_email.html
{% autoescape off %}
Hello,

You requested a reset password for your account at {{domain}}.

Please click the link below to reset your password:

http://{{domain}}{% url 'my_blog:reset_password' uidb64=uid token=token %} 

Thank you!
{% endautoescape %}